/**
 * Встроенные конфигурации режимов сетевого подключения
 * Обновлено с поддержкой GameFilter для Roblox и других игр
 */

const fs = require('fs');
const path = require('path');

// Проверка включен ли Game Filter (для поддержки игр типа Roblox)
function isGameFilterEnabled(binPath) {
  try {
    const flagFile = path.join(binPath, 'game_filter.enabled');
    return fs.existsSync(flagFile);
  } catch (e) {
    return true; // По умолчанию включен
  }
}

// Получить диапазон UDP портов в зависимости от Game Filter
function getGameFilterPorts(binPath) {
  if (isGameFilterEnabled(binPath)) {
    return '1024-65535'; // Полный диапазон для игр (Roblox и др.)
  }
  return '12'; // Минимальный диапазон
}

// Функция для генерации аргументов с путями
function generateArgs(config, binPath, listsPath, gameFilterPorts) {
  const args = [];
  
  for (const arg of config) {
    let processed = arg;
    // Заменяем плейсхолдеры на реальные пути
    processed = processed.replace(/{BIN}/g, binPath + '\\');
    processed = processed.replace(/{LISTS}/g, listsPath + '\\');
    // Заменяем плейсхолдер Game Filter на актуальный диапазон портов
    processed = processed.replace(/{GAME_FILTER}/g, gameFilterPorts);
    args.push(processed);
  }
  
  return args;
}

// Обновленные конфигурации с поддержкой GameFilter для Roblox
const BYPASS_CONFIGS = {
  'general': {
    name: 'Основной',
    description: 'Стандартный метод подключения с поддержкой игр',
    args: [
      '--wf-tcp=80,443,2053,2083,2087,2096,8443,{GAME_FILTER}',
      '--wf-udp=443,19294-19344,50000-50100,{GAME_FILTER}',
      '--filter-udp=443',
      '--hostlist={LISTS}list-general.txt',
      '--hostlist-exclude={LISTS}list-exclude.txt',
      '--ipset-exclude={LISTS}ipset-exclude.txt',
      '--dpi-desync=fake',
      '--dpi-desync-repeats=6',
      '--dpi-desync-fake-quic={BIN}quic_initial_www_google_com.bin',
      '--new',
      '--filter-udp=19294-19344,50000-50100',
      '--filter-l7=discord,stun',
      '--dpi-desync=fake',
      '--dpi-desync-repeats=6',
      '--new',
      '--filter-tcp=2053,2083,2087,2096,8443',
      '--hostlist-domains=discord.media',
      '--dpi-desync=multisplit',
      '--dpi-desync-split-seqovl=568',
      '--dpi-desync-split-pos=1',
      '--dpi-desync-split-seqovl-pattern={BIN}tls_clienthello_4pda_to.bin',
      '--new',
      '--filter-tcp=443',
      '--hostlist={LISTS}list-google.txt',
      '--ip-id=zero',
      '--dpi-desync=multisplit',
      '--dpi-desync-split-seqovl=681',
      '--dpi-desync-split-pos=1',
      '--dpi-desync-split-seqovl-pattern={BIN}tls_clienthello_www_google_com.bin',
      '--new',
      '--filter-tcp=80,443',
      '--hostlist={LISTS}list-general.txt',
      '--hostlist-exclude={LISTS}list-exclude.txt',
      '--ipset-exclude={LISTS}ipset-exclude.txt',
      '--dpi-desync=multisplit',
      '--dpi-desync-split-seqovl=568',
      '--dpi-desync-split-pos=1',
      '--dpi-desync-split-seqovl-pattern={BIN}tls_clienthello_4pda_to.bin',
      '--new',
      '--filter-udp=443',
      '--ipset={LISTS}ipset-all.txt',
      '--hostlist-exclude={LISTS}list-exclude.txt',
      '--ipset-exclude={LISTS}ipset-exclude.txt',
      '--dpi-desync=fake',
      '--dpi-desync-repeats=6',
      '--dpi-desync-fake-quic={BIN}quic_initial_www_google_com.bin',
      '--new',
      '--filter-tcp=80,443,{GAME_FILTER}',
      '--ipset={LISTS}ipset-all.txt',
      '--hostlist-exclude={LISTS}list-exclude.txt',
      '--ipset-exclude={LISTS}ipset-exclude.txt',
      '--dpi-desync=multisplit',
      '--dpi-desync-split-seqovl=568',
      '--dpi-desync-split-pos=1',
      '--dpi-desync-split-seqovl-pattern={BIN}tls_clienthello_4pda_to.bin',
      '--new',
      '--filter-udp={GAME_FILTER}',
      '--ipset={LISTS}ipset-all.txt',
      '--ipset-exclude={LISTS}ipset-exclude.txt',
      '--dpi-desync=fake',
      '--dpi-desync-autottl=2',
      '--dpi-desync-repeats=12',
      '--dpi-desync-any-protocol=1',
      '--dpi-desync-fake-unknown-udp={BIN}quic_initial_www_google_com.bin',
      '--dpi-desync-cutoff=n2'
    ]
  },

  'ALT': {
    name: 'Альтернативный 1',
    description: 'Вариант с fake+fakedsplit',
    args: [
      '--wf-tcp=80,443,2053,2083,2087,2096,8443,{GAME_FILTER}',
      '--wf-udp=443,19294-19344,50000-50100,{GAME_FILTER}',
      '--filter-udp=443',
      '--hostlist={LISTS}list-general.txt',
      '--hostlist-exclude={LISTS}list-exclude.txt',
      '--ipset-exclude={LISTS}ipset-exclude.txt',
      '--dpi-desync=fake',
      '--dpi-desync-repeats=6',
      '--dpi-desync-fake-quic={BIN}quic_initial_www_google_com.bin',
      '--new',
      '--filter-udp=19294-19344,50000-50100',
      '--filter-l7=discord,stun',
      '--dpi-desync=fake',
      '--dpi-desync-repeats=6',
      '--new',
      '--filter-tcp=2053,2083,2087,2096,8443',
      '--hostlist-domains=discord.media',
      '--dpi-desync=fake,fakedsplit',
      '--dpi-desync-repeats=6',
      '--dpi-desync-fooling=ts',
      '--dpi-desync-fakedsplit-pattern=0x00',
      '--dpi-desync-fake-tls={BIN}tls_clienthello_www_google_com.bin',
      '--new',
      '--filter-tcp=443',
      '--hostlist={LISTS}list-google.txt',
      '--ip-id=zero',
      '--dpi-desync=fake,fakedsplit',
      '--dpi-desync-repeats=6',
      '--dpi-desync-fooling=ts',
      '--dpi-desync-fakedsplit-pattern=0x00',
      '--dpi-desync-fake-tls={BIN}tls_clienthello_www_google_com.bin',
      '--new',
      '--filter-tcp=80,443',
      '--hostlist={LISTS}list-general.txt',
      '--hostlist-exclude={LISTS}list-exclude.txt',
      '--ipset-exclude={LISTS}ipset-exclude.txt',
      '--dpi-desync=fake,fakedsplit',
      '--dpi-desync-repeats=6',
      '--dpi-desync-fooling=ts',
      '--dpi-desync-fakedsplit-pattern=0x00',
      '--dpi-desync-fake-tls={BIN}tls_clienthello_www_google_com.bin',
      '--new',
      '--filter-udp=443',
      '--ipset={LISTS}ipset-all.txt',
      '--hostlist-exclude={LISTS}list-exclude.txt',
      '--ipset-exclude={LISTS}ipset-exclude.txt',
      '--dpi-desync=fake',
      '--dpi-desync-repeats=6',
      '--dpi-desync-fake-quic={BIN}quic_initial_www_google_com.bin',
      '--new',
      '--filter-tcp=80,443,{GAME_FILTER}',
      '--ipset={LISTS}ipset-all.txt',
      '--hostlist-exclude={LISTS}list-exclude.txt',
      '--ipset-exclude={LISTS}ipset-exclude.txt',
      '--dpi-desync=fake,fakedsplit',
      '--dpi-desync-repeats=6',
      '--dpi-desync-fooling=ts',
      '--dpi-desync-fakedsplit-pattern=0x00',
      '--dpi-desync-fake-tls={BIN}tls_clienthello_www_google_com.bin',
      '--new',
      '--filter-udp={GAME_FILTER}',
      '--ipset={LISTS}ipset-all.txt',
      '--ipset-exclude={LISTS}ipset-exclude.txt',
      '--dpi-desync=fake',
      '--dpi-desync-autottl=2',
      '--dpi-desync-repeats=12',
      '--dpi-desync-any-protocol=1',
      '--dpi-desync-fake-unknown-udp={BIN}quic_initial_www_google_com.bin',
      '--dpi-desync-cutoff=n2'
    ]
  },

  'ALT2': {
    name: 'Альтернативный 2',
    description: 'Вариант с split-pos=2',
    args: [
      '--wf-tcp=80,443,2053,2083,2087,2096,8443,{GAME_FILTER}',
      '--wf-udp=443,19294-19344,50000-50100,{GAME_FILTER}',
      '--filter-udp=443',
      '--hostlist={LISTS}list-general.txt',
      '--hostlist-exclude={LISTS}list-exclude.txt',
      '--ipset-exclude={LISTS}ipset-exclude.txt',
      '--dpi-desync=fake',
      '--dpi-desync-repeats=6',
      '--dpi-desync-fake-quic={BIN}quic_initial_www_google_com.bin',
      '--new',
      '--filter-udp=19294-19344,50000-50100',
      '--filter-l7=discord,stun',
      '--dpi-desync=fake',
      '--dpi-desync-repeats=6',
      '--new',
      '--filter-tcp=2053,2083,2087,2096,8443',
      '--hostlist-domains=discord.media',
      '--dpi-desync=multisplit',
      '--dpi-desync-split-seqovl=652',
      '--dpi-desync-split-pos=2',
      '--dpi-desync-split-seqovl-pattern={BIN}tls_clienthello_www_google_com.bin',
      '--new',
      '--filter-tcp=443',
      '--hostlist={LISTS}list-google.txt',
      '--ip-id=zero',
      '--dpi-desync=multisplit',
      '--dpi-desync-split-seqovl=652',
      '--dpi-desync-split-pos=2',
      '--dpi-desync-split-seqovl-pattern={BIN}tls_clienthello_www_google_com.bin',
      '--new',
      '--filter-tcp=80,443',
      '--hostlist={LISTS}list-general.txt',
      '--hostlist-exclude={LISTS}list-exclude.txt',
      '--ipset-exclude={LISTS}ipset-exclude.txt',
      '--dpi-desync=multisplit',
      '--dpi-desync-split-seqovl=652',
      '--dpi-desync-split-pos=2',
      '--dpi-desync-split-seqovl-pattern={BIN}tls_clienthello_www_google_com.bin',
      '--new',
      '--filter-udp=443',
      '--ipset={LISTS}ipset-all.txt',
      '--hostlist-exclude={LISTS}list-exclude.txt',
      '--ipset-exclude={LISTS}ipset-exclude.txt',
      '--dpi-desync=fake',
      '--dpi-desync-repeats=6',
      '--dpi-desync-fake-quic={BIN}quic_initial_www_google_com.bin',
      '--new',
      '--filter-tcp=80,443,{GAME_FILTER}',
      '--ipset={LISTS}ipset-all.txt',
      '--hostlist-exclude={LISTS}list-exclude.txt',
      '--ipset-exclude={LISTS}ipset-exclude.txt',
      '--dpi-desync=multisplit',
      '--dpi-desync-split-seqovl=652',
      '--dpi-desync-split-pos=2',
      '--dpi-desync-split-seqovl-pattern={BIN}tls_clienthello_www_google_com.bin',
      '--new',
      '--filter-udp={GAME_FILTER}',
      '--ipset={LISTS}ipset-all.txt',
      '--ipset-exclude={LISTS}ipset-exclude.txt',
      '--dpi-desync=fake',
      '--dpi-desync-autottl=2',
      '--dpi-desync-repeats=12',
      '--dpi-desync-any-protocol=1',
      '--dpi-desync-fake-unknown-udp={BIN}quic_initial_www_google_com.bin',
      '--dpi-desync-cutoff=n2'
    ]
  },

  'ALT3': {
    name: 'Альтернативный 3',
    description: 'Вариант с fakedsplit+autottl',
    args: [
      '--wf-tcp=80,443,2053,2083,2087,2096,8443,{GAME_FILTER}',
      '--wf-udp=443,19294-19344,50000-50100,{GAME_FILTER}',
      '--filter-udp=443',
      '--hostlist={LISTS}list-general.txt',
      '--hostlist-exclude={LISTS}list-exclude.txt',
      '--ipset-exclude={LISTS}ipset-exclude.txt',
      '--dpi-desync=fake',
      '--dpi-desync-repeats=6',
      '--dpi-desync-fake-quic={BIN}quic_initial_www_google_com.bin',
      '--new',
      '--filter-udp=19294-19344,50000-50100',
      '--filter-l7=discord,stun',
      '--dpi-desync=fake',
      '--dpi-desync-repeats=6',
      '--new',
      '--filter-tcp=2053,2083,2087,2096,8443',
      '--hostlist-domains=discord.media',
      '--dpi-desync=fakedsplit',
      '--dpi-desync-split-pos=1',
      '--dpi-desync-autottl',
      '--dpi-desync-fooling=badseq',
      '--dpi-desync-repeats=8',
      '--new',
      '--filter-tcp=443',
      '--hostlist={LISTS}list-google.txt',
      '--ip-id=zero',
      '--dpi-desync=fakedsplit',
      '--dpi-desync-split-pos=1',
      '--dpi-desync-autottl',
      '--dpi-desync-fooling=badseq',
      '--dpi-desync-repeats=8',
      '--new',
      '--filter-tcp=80,443',
      '--hostlist={LISTS}list-general.txt',
      '--hostlist-exclude={LISTS}list-exclude.txt',
      '--ipset-exclude={LISTS}ipset-exclude.txt',
      '--dpi-desync=fakedsplit',
      '--dpi-desync-split-pos=1',
      '--dpi-desync-autottl',
      '--dpi-desync-fooling=badseq',
      '--dpi-desync-repeats=8',
      '--new',
      '--filter-udp=443',
      '--ipset={LISTS}ipset-all.txt',
      '--hostlist-exclude={LISTS}list-exclude.txt',
      '--ipset-exclude={LISTS}ipset-exclude.txt',
      '--dpi-desync=fake',
      '--dpi-desync-repeats=6',
      '--dpi-desync-fake-quic={BIN}quic_initial_www_google_com.bin',
      '--new',
      '--filter-tcp=80,443,{GAME_FILTER}',
      '--ipset={LISTS}ipset-all.txt',
      '--hostlist-exclude={LISTS}list-exclude.txt',
      '--ipset-exclude={LISTS}ipset-exclude.txt',
      '--dpi-desync=fakedsplit',
      '--dpi-desync-split-pos=1',
      '--dpi-desync-autottl',
      '--dpi-desync-fooling=badseq',
      '--dpi-desync-repeats=8',
      '--new',
      '--filter-udp={GAME_FILTER}',
      '--ipset={LISTS}ipset-all.txt',
      '--ipset-exclude={LISTS}ipset-exclude.txt',
      '--dpi-desync=fake',
      '--dpi-desync-autottl=2',
      '--dpi-desync-repeats=10',
      '--dpi-desync-any-protocol=1',
      '--dpi-desync-fake-unknown-udp={BIN}quic_initial_www_google_com.bin',
      '--dpi-desync-cutoff=n2'
    ]
  },

  'ALT4': {
    name: 'Альтернативный 4',
    description: 'Вариант с fake+multisplit+badseq',
    args: [
      '--wf-tcp=80,443,2053,2083,2087,2096,8443,{GAME_FILTER}',
      '--wf-udp=443,19294-19344,50000-50100,{GAME_FILTER}',
      '--filter-udp=443',
      '--hostlist={LISTS}list-general.txt',
      '--hostlist-exclude={LISTS}list-exclude.txt',
      '--ipset-exclude={LISTS}ipset-exclude.txt',
      '--dpi-desync=fake',
      '--dpi-desync-repeats=6',
      '--dpi-desync-fake-quic={BIN}quic_initial_www_google_com.bin',
      '--new',
      '--filter-udp=19294-19344,50000-50100',
      '--filter-l7=discord,stun',
      '--dpi-desync=fake',
      '--dpi-desync-repeats=6',
      '--new',
      '--filter-tcp=2053,2083,2087,2096,8443',
      '--hostlist-domains=discord.media',
      '--dpi-desync=fake,multisplit',
      '--dpi-desync-repeats=6',
      '--dpi-desync-fooling=badseq',
      '--dpi-desync-badseq-increment=1000',
      '--dpi-desync-fake-tls={BIN}tls_clienthello_www_google_com.bin',
      '--new',
      '--filter-tcp=443',
      '--hostlist={LISTS}list-google.txt',
      '--ip-id=zero',
      '--dpi-desync=fake,multisplit',
      '--dpi-desync-repeats=6',
      '--dpi-desync-fooling=badseq',
      '--dpi-desync-badseq-increment=1000',
      '--dpi-desync-fake-tls={BIN}tls_clienthello_www_google_com.bin',
      '--new',
      '--filter-tcp=80,443',
      '--hostlist={LISTS}list-general.txt',
      '--hostlist-exclude={LISTS}list-exclude.txt',
      '--ipset-exclude={LISTS}ipset-exclude.txt',
      '--dpi-desync=fake,multisplit',
      '--dpi-desync-repeats=6',
      '--dpi-desync-fooling=badseq',
      '--dpi-desync-badseq-increment=1000',
      '--dpi-desync-fake-tls={BIN}tls_clienthello_www_google_com.bin',
      '--new',
      '--filter-udp=443',
      '--ipset={LISTS}ipset-all.txt',
      '--hostlist-exclude={LISTS}list-exclude.txt',
      '--ipset-exclude={LISTS}ipset-exclude.txt',
      '--dpi-desync=fake',
      '--dpi-desync-repeats=6',
      '--dpi-desync-fake-quic={BIN}quic_initial_www_google_com.bin',
      '--new',
      '--filter-tcp=80,443,{GAME_FILTER}',
      '--ipset={LISTS}ipset-all.txt',
      '--hostlist-exclude={LISTS}list-exclude.txt',
      '--ipset-exclude={LISTS}ipset-exclude.txt',
      '--dpi-desync=fake,multisplit',
      '--dpi-desync-repeats=6',
      '--dpi-desync-fooling=badseq',
      '--dpi-desync-badseq-increment=1000',
      '--dpi-desync-fake-tls={BIN}tls_clienthello_www_google_com.bin',
      '--new',
      '--filter-udp={GAME_FILTER}',
      '--ipset={LISTS}ipset-all.txt',
      '--ipset-exclude={LISTS}ipset-exclude.txt',
      '--dpi-desync=fake',
      '--dpi-desync-autottl=2',
      '--dpi-desync-repeats=10',
      '--dpi-desync-any-protocol=1',
      '--dpi-desync-fake-unknown-udp={BIN}quic_initial_www_google_com.bin',
      '--dpi-desync-cutoff=n2'
    ]
  },

  'ALT5': {
    name: 'Альтернативный 5',
    description: 'Упрощенный вариант (НЕ РЕКОМЕНДУЕТСЯ)',
    args: [
      '--wf-tcp=443,2053,2083,2087,2096,8443,{GAME_FILTER}',
      '--wf-udp=443,19294-19344,50000-50100,{GAME_FILTER}',
      '--filter-udp=443',
      '--hostlist={LISTS}list-general.txt',
      '--hostlist-exclude={LISTS}list-exclude.txt',
      '--ipset-exclude={LISTS}ipset-exclude.txt',
      '--dpi-desync=fake',
      '--dpi-desync-repeats=6',
      '--dpi-desync-fake-quic={BIN}quic_initial_www_google_com.bin',
      '--new',
      '--filter-udp=19294-19344,50000-50100',
      '--filter-l7=discord,stun',
      '--dpi-desync=fake',
      '--dpi-desync-repeats=6',
      '--new',
      '--filter-l3=ipv4',
      '--filter-tcp=443,2053,2083,2087,2096,8443,{GAME_FILTER}',
      '--hostlist-exclude={LISTS}list-exclude.txt',
      '--ipset-exclude={LISTS}ipset-exclude.txt',
      '--dpi-desync=syndata,multidisorder',
      '--new',
      '--filter-udp=443',
      '--ipset={LISTS}ipset-all.txt',
      '--hostlist-exclude={LISTS}list-exclude.txt',
      '--ipset-exclude={LISTS}ipset-exclude.txt',
      '--dpi-desync=fake',
      '--dpi-desync-repeats=6',
      '--dpi-desync-fake-quic={BIN}quic_initial_www_google_com.bin',
      '--new',
      '--filter-udp={GAME_FILTER}',
      '--ipset={LISTS}ipset-all.txt',
      '--ipset-exclude={LISTS}ipset-exclude.txt',
      '--dpi-desync=fake',
      '--dpi-desync-autottl=2',
      '--dpi-desync-repeats=14',
      '--dpi-desync-any-protocol=1',
      '--dpi-desync-fake-unknown-udp={BIN}quic_initial_www_google_com.bin',
      '--dpi-desync-cutoff=n3'
    ]
  },

  'ALT6': {
    name: 'Альтернативный 6',
    description: 'Вариант с seqovl=681',
    args: [
      '--wf-tcp=80,443,2053,2083,2087,2096,8443,{GAME_FILTER}',
      '--wf-udp=443,19294-19344,50000-50100,{GAME_FILTER}',
      '--filter-udp=443',
      '--hostlist={LISTS}list-general.txt',
      '--hostlist-exclude={LISTS}list-exclude.txt',
      '--ipset-exclude={LISTS}ipset-exclude.txt',
      '--dpi-desync=fake',
      '--dpi-desync-repeats=6',
      '--dpi-desync-fake-quic={BIN}quic_initial_www_google_com.bin',
      '--new',
      '--filter-udp=19294-19344,50000-50100',
      '--filter-l7=discord,stun',
      '--dpi-desync=fake',
      '--dpi-desync-repeats=6',
      '--new',
      '--filter-tcp=2053,2083,2087,2096,8443',
      '--hostlist-domains=discord.media',
      '--dpi-desync=multisplit',
      '--dpi-desync-split-seqovl=681',
      '--dpi-desync-split-pos=1',
      '--dpi-desync-split-seqovl-pattern={BIN}tls_clienthello_www_google_com.bin',
      '--new',
      '--filter-tcp=443',
      '--hostlist={LISTS}list-google.txt',
      '--ip-id=zero',
      '--dpi-desync=multisplit',
      '--dpi-desync-split-seqovl=681',
      '--dpi-desync-split-pos=1',
      '--dpi-desync-split-seqovl-pattern={BIN}tls_clienthello_www_google_com.bin',
      '--new',
      '--filter-tcp=80,443',
      '--hostlist={LISTS}list-general.txt',
      '--hostlist-exclude={LISTS}list-exclude.txt',
      '--ipset-exclude={LISTS}ipset-exclude.txt',
      '--dpi-desync=multisplit',
      '--dpi-desync-split-seqovl=681',
      '--dpi-desync-split-pos=1',
      '--dpi-desync-split-seqovl-pattern={BIN}tls_clienthello_www_google_com.bin',
      '--new',
      '--filter-udp=443',
      '--ipset={LISTS}ipset-all.txt',
      '--hostlist-exclude={LISTS}list-exclude.txt',
      '--ipset-exclude={LISTS}ipset-exclude.txt',
      '--dpi-desync=fake',
      '--dpi-desync-repeats=6',
      '--dpi-desync-fake-quic={BIN}quic_initial_www_google_com.bin',
      '--new',
      '--filter-tcp=80,443,{GAME_FILTER}',
      '--ipset={LISTS}ipset-all.txt',
      '--hostlist-exclude={LISTS}list-exclude.txt',
      '--ipset-exclude={LISTS}ipset-exclude.txt',
      '--dpi-desync=multisplit',
      '--dpi-desync-split-seqovl=681',
      '--dpi-desync-split-pos=1',
      '--dpi-desync-split-seqovl-pattern={BIN}tls_clienthello_www_google_com.bin',
      '--new',
      '--filter-udp={GAME_FILTER}',
      '--ipset={LISTS}ipset-all.txt',
      '--ipset-exclude={LISTS}ipset-exclude.txt',
      '--dpi-desync=fake',
      '--dpi-desync-autottl=2',
      '--dpi-desync-repeats=12',
      '--dpi-desync-any-protocol=1',
      '--dpi-desync-fake-unknown-udp={BIN}quic_initial_www_google_com.bin',
      '--dpi-desync-cutoff=n2'
    ]
  },

  'ALT7': {
    name: 'Альтернативный 7 (Рекомендуется)',
    description: 'Улучшенный вариант с sniext+1 для Roblox',
    args: [
      '--wf-tcp=80,443,2053,2083,2087,2096,8443,{GAME_FILTER}',
      '--wf-udp=443,19294-19344,50000-50100,{GAME_FILTER}',
      '--filter-udp=443',
      '--hostlist={LISTS}list-general.txt',
      '--hostlist-exclude={LISTS}list-exclude.txt',
      '--ipset-exclude={LISTS}ipset-exclude.txt',
      '--dpi-desync=fake',
      '--dpi-desync-repeats=6',
      '--dpi-desync-fake-quic={BIN}quic_initial_www_google_com.bin',
      '--new',
      '--filter-udp=19294-19344,50000-50100',
      '--filter-l7=discord,stun',
      '--dpi-desync=fake',
      '--dpi-desync-repeats=6',
      '--new',
      '--filter-tcp=2053,2083,2087,2096,8443',
      '--hostlist-domains=discord.media',
      '--dpi-desync=multisplit',
      '--dpi-desync-split-pos=2,sniext+1',
      '--dpi-desync-split-seqovl=679',
      '--dpi-desync-split-seqovl-pattern={BIN}tls_clienthello_www_google_com.bin',
      '--new',
      '--filter-tcp=443',
      '--hostlist={LISTS}list-google.txt',
      '--ip-id=zero',
      '--dpi-desync=multisplit',
      '--dpi-desync-split-pos=2,sniext+1',
      '--dpi-desync-split-seqovl=679',
      '--dpi-desync-split-seqovl-pattern={BIN}tls_clienthello_www_google_com.bin',
      '--new',
      '--filter-tcp=80,443',
      '--hostlist={LISTS}list-general.txt',
      '--hostlist-exclude={LISTS}list-exclude.txt',
      '--ipset-exclude={LISTS}ipset-exclude.txt',
      '--dpi-desync=multisplit',
      '--dpi-desync-split-pos=2,sniext+1',
      '--dpi-desync-split-seqovl=679',
      '--dpi-desync-split-seqovl-pattern={BIN}tls_clienthello_www_google_com.bin',
      '--new',
      '--filter-udp=443',
      '--ipset={LISTS}ipset-all.txt',
      '--hostlist-exclude={LISTS}list-exclude.txt',
      '--ipset-exclude={LISTS}ipset-exclude.txt',
      '--dpi-desync=fake',
      '--dpi-desync-repeats=6',
      '--dpi-desync-fake-quic={BIN}quic_initial_www_google_com.bin',
      '--new',
      '--filter-tcp=80,443,{GAME_FILTER}',
      '--ipset={LISTS}ipset-all.txt',
      '--hostlist-exclude={LISTS}list-exclude.txt',
      '--ipset-exclude={LISTS}ipset-exclude.txt',
      '--dpi-desync=syndata',
      '--new',
      '--filter-udp={GAME_FILTER}',
      '--ipset={LISTS}ipset-all.txt',
      '--ipset-exclude={LISTS}ipset-exclude.txt',
      '--dpi-desync=fake',
      '--dpi-desync-autottl=2',
      '--dpi-desync-repeats=12',
      '--dpi-desync-any-protocol=1',
      '--dpi-desync-fake-unknown-udp={BIN}quic_initial_www_google_com.bin',
      '--dpi-desync-cutoff=n2'
    ]
  },

  'ALT8': {
    name: 'Альтернативный 8',
    description: 'Вариант с fake-tls-mod=none',
    args: [
      '--wf-tcp=80,443,2053,2083,2087,2096,8443,{GAME_FILTER}',
      '--wf-udp=443,19294-19344,50000-50100,{GAME_FILTER}',
      '--filter-udp=443',
      '--hostlist={LISTS}list-general.txt',
      '--hostlist-exclude={LISTS}list-exclude.txt',
      '--ipset-exclude={LISTS}ipset-exclude.txt',
      '--dpi-desync=fake',
      '--dpi-desync-repeats=6',
      '--dpi-desync-fake-quic={BIN}quic_initial_www_google_com.bin',
      '--new',
      '--filter-udp=19294-19344,50000-50100',
      '--filter-l7=discord,stun',
      '--dpi-desync=fake',
      '--dpi-desync-repeats=6',
      '--new',
      '--filter-tcp=2053,2083,2087,2096,8443',
      '--hostlist-domains=discord.media',
      '--dpi-desync=fake',
      '--dpi-desync-fake-tls-mod=none',
      '--dpi-desync-repeats=6',
      '--dpi-desync-fooling=badseq',
      '--dpi-desync-badseq-increment=2',
      '--new',
      '--filter-tcp=443',
      '--hostlist={LISTS}list-google.txt',
      '--ip-id=zero',
      '--dpi-desync=fake',
      '--dpi-desync-fake-tls-mod=none',
      '--dpi-desync-repeats=6',
      '--dpi-desync-fooling=badseq',
      '--dpi-desync-badseq-increment=2',
      '--new',
      '--filter-tcp=80,443',
      '--hostlist={LISTS}list-general.txt',
      '--hostlist-exclude={LISTS}list-exclude.txt',
      '--ipset-exclude={LISTS}ipset-exclude.txt',
      '--dpi-desync=fake',
      '--dpi-desync-fake-tls-mod=none',
      '--dpi-desync-repeats=6',
      '--dpi-desync-fooling=badseq',
      '--dpi-desync-badseq-increment=2',
      '--new',
      '--filter-udp=443',
      '--ipset={LISTS}ipset-all.txt',
      '--hostlist-exclude={LISTS}list-exclude.txt',
      '--ipset-exclude={LISTS}ipset-exclude.txt',
      '--dpi-desync=fake',
      '--dpi-desync-repeats=6',
      '--dpi-desync-fake-quic={BIN}quic_initial_www_google_com.bin',
      '--new',
      '--filter-tcp=80,443,{GAME_FILTER}',
      '--ipset={LISTS}ipset-all.txt',
      '--hostlist-exclude={LISTS}list-exclude.txt',
      '--ipset-exclude={LISTS}ipset-exclude.txt',
      '--dpi-desync=fake',
      '--dpi-desync-fake-tls-mod=none',
      '--dpi-desync-repeats=6',
      '--dpi-desync-fooling=badseq',
      '--dpi-desync-badseq-increment=2',
      '--new',
      '--filter-udp={GAME_FILTER}',
      '--ipset={LISTS}ipset-all.txt',
      '--ipset-exclude={LISTS}ipset-exclude.txt',
      '--dpi-desync=fake',
      '--dpi-desync-autottl=2',
      '--dpi-desync-repeats=12',
      '--dpi-desync-any-protocol=1',
      '--dpi-desync-fake-unknown-udp={BIN}quic_initial_www_google_com.bin',
      '--dpi-desync-cutoff=n2'
    ]
  },

  'ALT9': {
    name: 'Альтернативный 9',
    description: 'Вариант с hostfakesplit',
    args: [
      '--wf-tcp=80,443,2053,2083,2087,2096,8443,{GAME_FILTER}',
      '--wf-udp=443,19294-19344,50000-50100,{GAME_FILTER}',
      '--filter-udp=443',
      '--hostlist={LISTS}list-general.txt',
      '--hostlist-exclude={LISTS}list-exclude.txt',
      '--ipset-exclude={LISTS}ipset-exclude.txt',
      '--dpi-desync=fake',
      '--dpi-desync-repeats=6',
      '--dpi-desync-fake-quic={BIN}quic_initial_www_google_com.bin',
      '--new',
      '--filter-udp=19294-19344,50000-50100',
      '--filter-l7=discord,stun',
      '--dpi-desync=fake',
      '--dpi-desync-repeats=6',
      '--new',
      '--filter-tcp=2053,2083,2087,2096,8443',
      '--hostlist-domains=discord.media',
      '--dpi-desync=hostfakesplit',
      '--dpi-desync-repeats=4',
      '--dpi-desync-fooling=ts',
      '--dpi-desync-hostfakesplit-mod=host=ozon.ru',
      '--new',
      '--filter-tcp=443',
      '--hostlist={LISTS}list-google.txt',
      '--ip-id=zero',
      '--dpi-desync=hostfakesplit',
      '--dpi-desync-repeats=4',
      '--dpi-desync-fooling=ts',
      '--dpi-desync-hostfakesplit-mod=host=www.google.com',
      '--new',
      '--filter-tcp=80,443',
      '--hostlist={LISTS}list-general.txt',
      '--hostlist-exclude={LISTS}list-exclude.txt',
      '--ipset-exclude={LISTS}ipset-exclude.txt',
      '--dpi-desync=hostfakesplit',
      '--dpi-desync-repeats=4',
      '--dpi-desync-fooling=ts,md5sig',
      '--dpi-desync-hostfakesplit-mod=host=ozon.ru',
      '--new',
      '--filter-udp=443',
      '--ipset={LISTS}ipset-all.txt',
      '--hostlist-exclude={LISTS}list-exclude.txt',
      '--ipset-exclude={LISTS}ipset-exclude.txt',
      '--dpi-desync=fake',
      '--dpi-desync-repeats=6',
      '--dpi-desync-fake-quic={BIN}quic_initial_www_google_com.bin',
      '--new',
      '--filter-tcp=80,443,{GAME_FILTER}',
      '--ipset={LISTS}ipset-all.txt',
      '--hostlist-exclude={LISTS}list-exclude.txt',
      '--ipset-exclude={LISTS}ipset-exclude.txt',
      '--dpi-desync=hostfakesplit',
      '--dpi-desync-repeats=4',
      '--dpi-desync-fooling=ts',
      '--dpi-desync-hostfakesplit-mod=host=ozon.ru',
      '--new',
      '--filter-udp={GAME_FILTER}',
      '--ipset={LISTS}ipset-all.txt',
      '--ipset-exclude={LISTS}ipset-exclude.txt',
      '--dpi-desync=fake',
      '--dpi-desync-autottl=2',
      '--dpi-desync-repeats=12',
      '--dpi-desync-any-protocol=1',
      '--dpi-desync-fake-unknown-udp={BIN}quic_initial_www_google_com.bin',
      '--dpi-desync-cutoff=n2'
    ]
  },

  'ALT10': {
    name: 'Альтернативный 10',
    description: 'Расширенный вариант с fake-tls-mod',
    args: [
      '--wf-tcp=80,443,2053,2083,2087,2096,8443,{GAME_FILTER}',
      '--wf-udp=443,19294-19344,50000-50100,{GAME_FILTER}',
      '--filter-udp=443',
      '--hostlist={LISTS}list-general.txt',
      '--hostlist-exclude={LISTS}list-exclude.txt',
      '--ipset-exclude={LISTS}ipset-exclude.txt',
      '--dpi-desync=fake',
      '--dpi-desync-repeats=6',
      '--dpi-desync-fake-quic={BIN}quic_initial_www_google_com.bin',
      '--new',
      '--filter-udp=19294-19344,50000-50100',
      '--filter-l7=discord,stun',
      '--dpi-desync=fake',
      '--dpi-desync-repeats=6',
      '--new',
      '--filter-tcp=2053,2083,2087,2096,8443',
      '--hostlist-domains=discord.media',
      '--dpi-desync=fake',
      '--dpi-desync-repeats=6',
      '--dpi-desync-fooling=ts',
      '--dpi-desync-fake-tls={BIN}tls_clienthello_4pda_to.bin',
      '--dpi-desync-fake-tls-mod=none',
      '--new',
      '--filter-tcp=443',
      '--hostlist={LISTS}list-google.txt',
      '--ip-id=zero',
      '--dpi-desync=fake',
      '--dpi-desync-repeats=6',
      '--dpi-desync-fooling=ts',
      '--dpi-desync-fake-tls={BIN}tls_clienthello_www_google_com.bin',
      '--new',
      '--filter-tcp=80,443',
      '--hostlist={LISTS}list-general.txt',
      '--hostlist-exclude={LISTS}list-exclude.txt',
      '--ipset-exclude={LISTS}ipset-exclude.txt',
      '--dpi-desync=fake',
      '--dpi-desync-repeats=6',
      '--dpi-desync-fooling=ts',
      '--dpi-desync-fake-tls={BIN}tls_clienthello_4pda_to.bin',
      '--dpi-desync-fake-tls-mod=none',
      '--new',
      '--filter-udp=443',
      '--ipset={LISTS}ipset-all.txt',
      '--hostlist-exclude={LISTS}list-exclude.txt',
      '--ipset-exclude={LISTS}ipset-exclude.txt',
      '--dpi-desync=fake',
      '--dpi-desync-repeats=6',
      '--dpi-desync-fake-quic={BIN}quic_initial_www_google_com.bin',
      '--new',
      '--filter-tcp=80,443,{GAME_FILTER}',
      '--ipset={LISTS}ipset-all.txt',
      '--hostlist-exclude={LISTS}list-exclude.txt',
      '--ipset-exclude={LISTS}ipset-exclude.txt',
      '--dpi-desync=fake',
      '--dpi-desync-repeats=6',
      '--dpi-desync-fooling=ts',
      '--dpi-desync-fake-tls=!',
      '--dpi-desync-fake-tls-mod=rnd,sni=www.google.com',
      '--dpi-desync-fake-tls={BIN}tls_clienthello_4pda_to.bin',
      '--dpi-desync-fake-tls-mod=none',
      '--new',
      '--filter-udp={GAME_FILTER}',
      '--ipset={LISTS}ipset-all.txt',
      '--ipset-exclude={LISTS}ipset-exclude.txt',
      '--dpi-desync=fake',
      '--dpi-desync-autottl=2',
      '--dpi-desync-repeats=12',
      '--dpi-desync-any-protocol=1',
      '--dpi-desync-fake-unknown-udp={BIN}quic_initial_www_google_com.bin',
      '--dpi-desync-cutoff=n2'
    ]
  }
};

// Получить конфигурацию для режима
function getBypassConfig(mode, binPath, listsPath) {
  const config = BYPASS_CONFIGS[mode] || BYPASS_CONFIGS['general'];
  // Получаем диапазон UDP портов в зависимости от Game Filter
  const gameFilterPorts = getGameFilterPorts(binPath);
  return {
    name: config.name,
    description: config.description,
    args: generateArgs(config.args, binPath, listsPath, gameFilterPorts)
  };
}

// Получить список доступных режимов
function getAvailableModes() {
  return Object.entries(BYPASS_CONFIGS).map(([id, config]) => ({
    id,
    name: config.name,
    description: config.description
  }));
}

module.exports = {
  BYPASS_CONFIGS,
  getBypassConfig,
  getAvailableModes,
  generateArgs,
  isGameFilterEnabled,
  getGameFilterPorts
};
